### ISSUE TITLE
data3.cab not able to be found

### ISSUE THREAD

**Issue by ijcloran** [Zuzzuc/Battlefield-1942-installer#1]
I used to play Battlefield 1942 all the time as a younger kid and wanted to see if I could download it. Download works fine, it launches fine, but about 45% through installation, the installer says it can't find data3.cab. Am I doing something wrong? On macOS High Sierra.

**Comment by Zuzzuc** [comment]
Can you remove the files with `rm -rf $HOME/Documents/Battlefield\ 1942.iso /tmp/bf1942installer $HOME/Wine\ Files` and run the installer again? Please tell me if the problem persist

**Comment by Zuzzuc** [comment]
It appears as the precompiled wine files are corrupt. The game should be installed by default and should be ready to be played once the installer is finished.

I'll regenerate the wine files soon(this week) and upload them so it will work again.

**Comment by Zuzzuc** [comment]
I found a backup of the working wine files. They are pushed to the server now. Uninstall the files previously installed (the command i posted above) and perform a clean installation. It should work after that

**Comment by dotmick** [comment]
I'm still having the issue of data3.cab not being found :/

Any idea why?

**Comment by Zuzzuc** [comment]
Yes, there is currently a problem with my file server. I’m on vacation so I can not fix it atm. See the other open issue, I’ll post there when the problem is solved!

**Comment by dotmick** [comment]
Amazing thanks!
